import { Competition, Task, Deadline, User, ActivityLog, KnowledgeBaseArticle, DashboardStats } from "@/types";

export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "Ahmad Rizky",
    email: "ahmad@cygnus.id",
    role: "ADMIN",
    image: null,
    nim: "2101234567",
    faculty: "Teknik Informatika",
    skills: ["Frontend", "Backend", "AI/ML"],
    password: "password123",
  },
  {
    id: "user-2",
    name: "Budi Santoso",
    email: "budi@cygnus.id",
    role: "TEAM_LEADER",
    image: null,
    nim: "2101234568",
    faculty: "Sistem Informasi",
    skills: ["UI/UX", "Frontend", "Mobile"],
    password: "password123",
  },
  {
    id: "user-3",
    name: "Citra Dewi",
    email: "citra@cygnus.id",
    role: "MEMBER",
    image: null,
    nim: "2101234569",
    faculty: "Teknik Komputer",
    skills: ["Data Science", "Research", "Writing"],
    password: "password123",
  },
  {
    id: "user-4",
    name: "Diana Putri",
    email: "diana@cygnus.id",
    role: "MEMBER",
    image: null,
    nim: "2101234570",
    faculty: "Teknik Informatika",
    skills: ["Cyber Security", "CTF", "Backend"],
    password: "password123",
  },
  {
    id: "user-5",
    name: "Eko Prasetyo",
    email: "eko@cygnus.id",
    role: "MEMBER",
    image: null,
    nim: "2101234571",
    faculty: "Sistem Informasi",
    skills: ["Business Case", "Writing", "Research"],
    password: "password123",
  },
  {
    id: "user-6",
    name: "Jovan",
    email: "jovan@cygnus.id",
    role: "MEMBER",
    image: null,
    nim: "2101234572",
    faculty: "Teknik Informatika",
    skills: ["Frontend", "UI/UX"],
    password: "jovan123",
  },
  {
    id: "user-7",
    name: "Jonathan",
    email: "jonathan@cygnus.id",
    role: "ADMIN",
    image: null,
    nim: "2101234573",
    faculty: "Teknik Informatika",
    skills: ["Backend", "AI/ML", "Data Science"],
    password: "jonathan123",
  },
];

export const mockCompetitions: Competition[] = [
  {
    id: "comp-1",
    name: "Hackathon AI Indonesia 2026",
    organizer: "Google Developer Student Clubs",
    website: "https://hackathon-ai.id",
    level: "NATIONAL",
    category: "HACKATHON",
    description: "Kompetisi hackathon terbesar di Indonesia dengan fokus pada implementasi AI dalam berbagai sektor industri.",
    prizePool: "Rp 500.000.000",
    certificate: true,
    funding: true,
    incubation: true,
    status: "FINAL",
    startDate: new Date("2026-01-15"),
    endDate: new Date("2026-06-20"),
    createdAt: new Date("2025-12-01"),
    stages: [
      { id: "stage-1", name: "Monitoring", order: 1, status: "COMPLETED", startDate: new Date("2025-12-01"), endDate: new Date("2025-12-15"), description: "Mencari informasi dan mengevaluasi lomba" },
      { id: "stage-2", name: "Registrasi", order: 2, status: "COMPLETED", startDate: new Date("2025-12-16"), endDate: new Date("2026-01-10"), description: "Pendaftaran tim dan persyaratan" },
      { id: "stage-3", name: "Ideasi", order: 3, status: "COMPLETED", startDate: new Date("2026-01-11"), endDate: new Date("2026-01-25"), description: "Brainstorming dan pemilihan ide" },
      { id: "stage-4", name: "Proposal", order: 4, status: "COMPLETED", startDate: new Date("2026-01-26"), endDate: new Date("2026-02-15"), description: "Penulisan proposal awal" },
      { id: "stage-5", name: "Development", order: 5, status: "COMPLETED", startDate: new Date("2026-02-16"), endDate: new Date("2026-04-30"), description: "Pengembangan aplikasi/produk" },
      { id: "stage-6", name: "Testing", order: 6, status: "COMPLETED", startDate: new Date("2026-05-01"), endDate: new Date("2026-05-15"), description: "Testing dan debugging" },
      { id: "stage-7", name: "Presentation Deck", order: 7, status: "COMPLETED", startDate: new Date("2026-05-16"), endDate: new Date("2026-05-25"), description: "Persiapan presentasi" },
      { id: "stage-8", name: "Demo", order: 8, status: "COMPLETED", startDate: new Date("2026-05-26"), endDate: new Date("2026-06-05"), description: "Demo day dan presentasi" },
      { id: "stage-9", name: "Submission", order: 9, status: "IN_PROGRESS", startDate: new Date("2026-06-06"), endDate: new Date("2026-06-15"), description: "Final submission" },
      { id: "stage-10", name: "Final Pitch", order: 10, status: "PENDING", startDate: new Date("2026-06-16"), endDate: new Date("2026-06-18"), description: "Final pitch presentation" },
      { id: "stage-11", name: "Result", order: 11, status: "PENDING", startDate: new Date("2026-06-20"), endDate: new Date("2026-06-20"), description: "Pengumuman pemenang" },
    ],
    timeline: [
      { id: "tl-1", title: "Deadline Registrasi", date: new Date("2026-01-10"), type: "DEADLINE", description: "Batas akhir pendaftaran" },
      { id: "tl-2", title: "Meeting Kickoff", date: new Date("2026-01-12"), type: "MEETING", description: "Pertemuan awal tim" },
      { id: "tl-3", title: "Deadline Proposal", date: new Date("2026-02-15"), type: "SUBMISSION", description: "Pengumpulan proposal" },
      { id: "tl-4", title: "Progress Review", date: new Date("2026-03-15"), type: "MEETING", description: "Review progress pengembangan" },
      { id: "tl-5", title: "Demo Day", date: new Date("2026-06-05"), type: "PRESENTATION", description: "Presentasi demo aplikasi" },
      { id: "tl-6", title: "Final Submission", date: new Date("2026-06-15"), type: "SUBMISSION", description: "Pengumpulan final" },
      { id: "tl-7", title: "Final Pitch", date: new Date("2026-06-18"), type: "PRESENTATION", description: "Presentasi final" },
    ],
    tasks: [
      { id: "task-1", competitionId: "comp-1", title: "Research AI Models", description: "Mencari dan mengevaluasi model AI yang cocok", status: "DONE", priority: "HIGH", assigneeId: "user-1", assignee: mockUsers[0], dueDate: new Date("2026-01-20"), createdAt: new Date("2026-01-12"), comments: [] },
      { id: "task-2", competitionId: "comp-1", title: "Design UI/UX", description: "Membuat desain interface aplikasi", status: "DONE", priority: "HIGH", assigneeId: "user-2", assignee: mockUsers[1], dueDate: new Date("2026-02-05"), createdAt: new Date("2026-01-15"), comments: [] },
      { id: "task-3", competitionId: "comp-1", title: "Backend Development", description: "Membangun API dan database", status: "DONE", priority: "CRITICAL", assigneeId: "user-1", assignee: mockUsers[0], dueDate: new Date("2026-03-30"), createdAt: new Date("2026-02-01"), comments: [] },
      { id: "task-4", competitionId: "comp-1", title: "Frontend Implementation", description: "Implementasi UI ke kode", status: "DONE", priority: "HIGH", assigneeId: "user-2", assignee: mockUsers[1], dueDate: new Date("2026-04-15"), createdAt: new Date("2026-02-10"), comments: [] },
      { id: "task-5", competitionId: "comp-1", title: "AI Integration", description: "Integrasi model AI ke aplikasi", status: "DONE", priority: "CRITICAL", assigneeId: "user-3", assignee: mockUsers[2], dueDate: new Date("2026-04-20"), createdAt: new Date("2026-02-15"), comments: [] },
      { id: "task-6", competitionId: "comp-1", title: "Testing & QA", description: "Testing aplikasi dan bug fixes", status: "DONE", priority: "MEDIUM", assigneeId: "user-4", assignee: mockUsers[3], dueDate: new Date("2026-05-10"), createdAt: new Date("2026-04-01"), comments: [] },
      { id: "task-7", competitionId: "comp-1", title: "Presentation Deck", description: "Membuat slide presentasi", status: "IN_PROGRESS", priority: "HIGH", assigneeId: "user-5", assignee: mockUsers[4], dueDate: new Date("2026-06-10"), createdAt: new Date("2026-05-20"), comments: [] },
      { id: "task-8", competitionId: "comp-1", title: "Final Documentation", description: "Dokumentasi final project", status: "TODO", priority: "MEDIUM", assigneeId: "user-3", assignee: mockUsers[2], dueDate: new Date("2026-06-12"), createdAt: new Date("2026-06-01"), comments: [] },
    ],
    deadlines: [
      { id: "dl-1", competitionId: "comp-1", competition: null as any, title: "Deadline Registrasi", type: "REGISTRATION", date: new Date("2026-01-10"), description: "Batas akhir pendaftaran", daysRemaining: -153 },
      { id: "dl-2", competitionId: "comp-1", competition: null as any, title: "Deadline Proposal", type: "PROPOSAL", date: new Date("2026-02-15"), description: "Pengumpulan proposal awal", daysRemaining: -117 },
      { id: "dl-3", competitionId: "comp-1", competition: null as any, title: "Final Submission", type: "SUBMISSION", date: new Date("2026-06-15"), description: "Pengumpulan final project", daysRemaining: 3 },
      { id: "dl-4", competitionId: "comp-1", competition: null as any, title: "Final Presentation", type: "PRESENTATION", date: new Date("2026-06-18"), description: "Presentasi final", daysRemaining: 6 },
    ],
    teamMembers: [
      { id: "tm-1", userId: "user-1", role: "LEADER", joinedAt: new Date("2025-12-10"), user: mockUsers[0] },
      { id: "tm-2", userId: "user-2", role: "CO_LEADER", joinedAt: new Date("2025-12-12"), user: mockUsers[1] },
      { id: "tm-3", userId: "user-3", role: "MEMBER", joinedAt: new Date("2025-12-15"), user: mockUsers[2] },
      { id: "tm-4", userId: "user-4", role: "MEMBER", joinedAt: new Date("2025-12-15"), user: mockUsers[3] },
      { id: "tm-5", userId: "user-5", role: "MEMBER", joinedAt: new Date("2025-12-20"), user: mockUsers[4] },
    ],
    documents: [
      { id: "doc-1", competitionId: "comp-1", uploadedBy: "user-1", user: mockUsers[0], name: "Proposal_Awal.pdf", type: "PROPOSAL", url: "/docs/proposal-awal.pdf", size: 2048000, version: 1, createdAt: new Date("2026-02-10") },
      { id: "doc-2", competitionId: "comp-1", uploadedBy: "user-2", user: mockUsers[1], name: "Design_Mockup.fig", type: "OTHER", url: "/docs/design-mockup.fig", size: 5120000, version: 2, createdAt: new Date("2026-02-20") },
      { id: "doc-3", competitionId: "comp-1", uploadedBy: "user-3", user: mockUsers[2], name: "Research_Paper.pdf", type: "PAPER", url: "/docs/research-paper.pdf", size: 1536000, version: 1, createdAt: new Date("2026-03-01") },
      { id: "doc-4", competitionId: "comp-1", uploadedBy: "user-5", user: mockUsers[4], name: "Presentation_Deck.pptx", type: "PPT", url: "/docs/presentation-deck.pptx", size: 8192000, version: 3, createdAt: new Date("2026-06-05") },
    ],
    results: null,
  },
  {
    id: "comp-2",
    name: "National CTF Championship 2026",
    organizer: "Cyber Security Indonesia",
    website: "https://ctf-nasional.id",
    level: "NATIONAL",
    category: "CTF",
    description: "Kompetisi Capture The Flag tingkat nasional dengan berbagai kategori soal.",
    prizePool: "Rp 200.000.000",
    certificate: true,
    funding: false,
    incubation: false,
    status: "SELECTION_PROPOSAL",
    startDate: new Date("2026-03-01"),
    endDate: new Date("2026-08-30"),
    createdAt: new Date("2026-01-15"),
    stages: [
      { id: "stage-ctf-1", name: "Monitoring", order: 1, status: "COMPLETED", startDate: new Date("2026-01-15"), endDate: new Date("2026-02-15"), description: null },
      { id: "stage-ctf-2", name: "Registration", order: 2, status: "COMPLETED", startDate: new Date("2026-02-16"), endDate: new Date("2026-03-15"), description: null },
      { id: "stage-ctf-3", name: "Team Formation", order: 3, status: "COMPLETED", startDate: new Date("2026-03-01"), endDate: new Date("2026-03-20"), description: null },
      { id: "stage-ctf-4", name: "Preparation", order: 4, status: "IN_PROGRESS", startDate: new Date("2026-03-21"), endDate: new Date("2026-07-31"), description: null },
      { id: "stage-ctf-5", name: "Competition Day", order: 5, status: "PENDING", startDate: new Date("2026-08-15"), endDate: new Date("2026-08-17"), description: null },
      { id: "stage-ctf-6", name: "Flag Collection", order: 6, status: "PENDING", startDate: new Date("2026-08-15"), endDate: new Date("2026-08-17"), description: null },
      { id: "stage-ctf-7", name: "Scoring", order: 7, status: "PENDING", startDate: new Date("2026-08-18"), endDate: new Date("2026-08-20"), description: null },
      { id: "stage-ctf-8", name: "Result", order: 8, status: "PENDING", startDate: new Date("2026-08-25"), endDate: new Date("2026-08-30"), description: null },
    ],
    timeline: [
      { id: "tl-ctf-1", title: "Registration Deadline", date: new Date("2026-03-15"), type: "DEADLINE", description: "Batas akhir registrasi" },
      { id: "tl-ctf-2", title: "Preparation Phase", date: new Date("2026-04-01"), type: "MILESTONE", description: "Mulai persiapan intensif" },
      { id: "tl-ctf-3", title: "Competition Day", date: new Date("2026-08-15"), type: "DEADLINE", description: "Hari kompetisi" },
    ],
    tasks: [
      { id: "task-ctf-1", competitionId: "comp-2", title: "Setup CTF Environment", description: "Setup environment latihan", status: "DONE", priority: "HIGH", assigneeId: "user-4", assignee: mockUsers[3], dueDate: new Date("2026-03-25"), createdAt: new Date("2026-03-10"), comments: [] },
      { id: "task-ctf-2", competitionId: "comp-2", title: "Practice Web Exploitation", description: "Latihan soal web exploitation", status: "IN_PROGRESS", priority: "HIGH", assigneeId: "user-4", assignee: mockUsers[3], dueDate: new Date("2026-04-30"), createdAt: new Date("2026-03-20"), comments: [] },
      { id: "task-ctf-3", competitionId: "comp-2", title: "Practice Reverse Engineering", description: "Latihan reverse engineering", status: "TODO", priority: "MEDIUM", assigneeId: "user-1", assignee: mockUsers[0], dueDate: new Date("2026-05-15"), createdAt: new Date("2026-03-25"), comments: [] },
      { id: "task-ctf-4", competitionId: "comp-2", title: "Practice Cryptography", description: "Latihan kriptografi", status: "BACKLOG", priority: "MEDIUM", assigneeId: "user-3", assignee: mockUsers[2], dueDate: new Date("2026-06-01"), createdAt: new Date("2026-03-25"), comments: [] },
    ],
    deadlines: [
      { id: "dl-ctf-1", competitionId: "comp-2", competition: null as any, title: "Registration Deadline", type: "REGISTRATION", date: new Date("2026-03-15"), description: "Batas akhir registrasi", daysRemaining: -89 },
      { id: "dl-ctf-2", competitionId: "comp-2", competition: null as any, title: "Preparation Report", type: "OTHER", date: new Date("2026-07-31"), description: "Laporan persiapan tim", daysRemaining: 49 },
      { id: "dl-ctf-3", competitionId: "comp-2", competition: null as any, title: "Competition Day", type: "FINAL_ROUND", date: new Date("2026-08-15"), description: "Hari kompetisi", daysRemaining: 64 },
    ],
    teamMembers: [
      { id: "tm-ctf-1", userId: "user-4", role: "LEADER", joinedAt: new Date("2026-02-20"), user: mockUsers[3] },
      { id: "tm-ctf-2", userId: "user-1", role: "MEMBER", joinedAt: new Date("2026-02-25"), user: mockUsers[0] },
      { id: "tm-ctf-3", userId: "user-3", role: "MEMBER", joinedAt: new Date("2026-03-01"), user: mockUsers[2] },
    ],
    documents: [
      { id: "doc-ctf-1", competitionId: "comp-2", uploadedBy: "user-4", user: mockUsers[3], name: "CTF_Writeups.pdf", type: "REFERENCES", url: "/docs/ctf-writeups.pdf", size: 1024000, version: 1, createdAt: new Date("2026-03-15") },
    ],
    results: null,
  },
  {
    id: "comp-3",
    name: "International Research Competition 2026",
    organizer: "IEEE",
    website: "https://ieee-research.org",
    level: "INTERNATIONAL",
    category: "RESEARCH",
    description: "Kompetisi riset internasional dengan fokus pada teknologi terbaru.",
    prizePool: "$50,000",
    certificate: true,
    funding: true,
    incubation: true,
    status: "REGISTRATION",
    startDate: new Date("2026-04-01"),
    endDate: new Date("2026-12-15"),
    createdAt: new Date("2026-02-01"),
    stages: [
      { id: "stage-res-1", name: "Monitoring", order: 1, status: "COMPLETED", startDate: new Date("2026-02-01"), endDate: new Date("2026-02-28"), description: null },
      { id: "stage-res-2", name: "Topic Selection", order: 2, status: "COMPLETED", startDate: new Date("2026-03-01"), endDate: new Date("2026-03-20"), description: null },
      { id: "stage-res-3", name: "Literature Review", order: 3, status: "IN_PROGRESS", startDate: new Date("2026-03-21"), endDate: new Date("2026-05-15"), description: null },
      { id: "stage-res-4", name: "Research Design", order: 4, status: "PENDING", startDate: new Date("2026-05-16"), endDate: new Date("2026-06-30"), description: null },
      { id: "stage-res-5", name: "Data Collection", order: 5, status: "PENDING", startDate: new Date("2026-07-01"), endDate: new Date("2026-08-31"), description: null },
      { id: "stage-res-6", name: "Analysis", order: 6, status: "PENDING", startDate: new Date("2026-09-01"), endDate: new Date("2026-09-30"), description: null },
      { id: "stage-res-7", name: "Paper Writing", order: 7, status: "PENDING", startDate: new Date("2026-10-01"), endDate: new Date("2026-10-31"), description: null },
      { id: "stage-res-8", name: "Review", order: 8, status: "PENDING", startDate: new Date("2026-11-01"), endDate: new Date("2026-11-15"), description: null },
      { id: "stage-res-9", name: "Revision", order: 9, status: "PENDING", startDate: new Date("2026-11-16"), endDate: new Date("2026-11-30"), description: null },
      { id: "stage-res-10", name: "Submission", order: 10, status: "PENDING", startDate: new Date("2026-12-01"), endDate: new Date("2026-12-10"), description: null },
      { id: "stage-res-11", name: "Presentation", order: 11, status: "PENDING", startDate: new Date("2026-12-12"), endDate: new Date("2026-12-13"), description: null },
      { id: "stage-res-12", name: "Result", order: 12, status: "PENDING", startDate: new Date("2026-12-15"), endDate: new Date("2026-12-15"), description: null },
    ],
    timeline: [
      { id: "tl-res-1", title: "Registration Deadline", date: new Date("2026-04-15"), type: "DEADLINE", description: "Batas akhir registrasi" },
      { id: "tl-res-2", title: "Literature Review Complete", date: new Date("2026-05-15"), type: "MILESTONE", description: "Selesai literature review" },
      { id: "tl-res-3", title: "Paper Submission", date: new Date("2026-12-10"), type: "SUBMISSION", description: "Pengumpulan paper" },
    ],
    tasks: [
      { id: "task-res-1", competitionId: "comp-3", title: "Literature Review", description: "Review paper terkait", status: "IN_PROGRESS", priority: "HIGH", assigneeId: "user-3", assignee: mockUsers[2], dueDate: new Date("2026-05-15"), createdAt: new Date("2026-03-25"), comments: [] },
      { id: "task-res-2", competitionId: "comp-3", title: "Research Methodology", description: "Menyusun metodologi riset", status: "TODO", priority: "HIGH", assigneeId: "user-5", assignee: mockUsers[4], dueDate: new Date("2026-06-15"), createdAt: new Date("2026-03-25"), comments: [] },
      { id: "task-res-3", competitionId: "comp-3", title: "Data Collection Plan", description: "Rencana pengumpulan data", status: "BACKLOG", priority: "MEDIUM", assigneeId: "user-3", assignee: mockUsers[2], dueDate: new Date("2026-07-01"), createdAt: new Date("2026-03-25"), comments: [] },
    ],
    deadlines: [
      { id: "dl-res-1", competitionId: "comp-3", competition: null as any, title: "Registration Deadline", type: "REGISTRATION", date: new Date("2026-04-15"), description: "Batas akhir registrasi", daysRemaining: -59 },
      { id: "dl-res-2", competitionId: "comp-3", competition: null as any, title: "Literature Review", type: "OTHER", date: new Date("2026-05-15"), description: "Deadline literature review", daysRemaining: -29 },
      { id: "dl-res-3", competitionId: "comp-3", competition: null as any, title: "Paper Submission", type: "SUBMISSION", date: new Date("2026-12-10"), description: "Pengumpulan paper final", daysRemaining: 181 },
    ],
    teamMembers: [
      { id: "tm-res-1", userId: "user-3", role: "LEADER", joinedAt: new Date("2026-02-15"), user: mockUsers[2] },
      { id: "tm-res-2", userId: "user-5", role: "CO_LEADER", joinedAt: new Date("2026-02-20"), user: mockUsers[4] },
      { id: "tm-res-3", userId: "user-1", role: "MEMBER", joinedAt: new Date("2026-03-01"), user: mockUsers[0] },
    ],
    documents: [],
    results: null,
  },
  {
    id: "comp-4",
    name: "Business Case Competition Unair 2026",
    organizer: "Universitas Airlangga",
    website: "https://bcc.unair.ac.id",
    level: "REGIONAL",
    category: "BUSINESS_CASE",
    description: "Kompetisi analisis kasus bisnis tingkat regional.",
    prizePool: "Rp 75.000.000",
    certificate: true,
    funding: false,
    incubation: false,
    status: "MONITORING",
    startDate: null,
    endDate: null,
    createdAt: new Date("2026-05-01"),
    stages: [
      { id: "stage-bcc-1", name: "Monitoring", order: 1, status: "IN_PROGRESS", startDate: new Date("2026-05-01"), endDate: null, description: "Mengevaluasi lomba" },
    ],
    timeline: [],
    tasks: [
      { id: "task-bcc-1", competitionId: "comp-4", title: "Evaluate Competition", description: "Mengevaluasi apakah lomba worth it", status: "IN_PROGRESS", priority: "MEDIUM", assigneeId: "user-5", assignee: mockUsers[4], dueDate: new Date("2026-06-20"), createdAt: new Date("2026-05-10"), comments: [] },
    ],
    deadlines: [
      { id: "dl-bcc-1", competitionId: "comp-4", competition: null as any, title: "Registration Opens", type: "REGISTRATION", date: new Date("2026-07-01"), description: "Pendaftaran dibuka", daysRemaining: 19 },
    ],
    teamMembers: [
      { id: "tm-bcc-1", userId: "user-5", role: "LEADER", joinedAt: new Date("2026-05-05"), user: mockUsers[4] },
      { id: "tm-bcc-2", userId: "user-2", role: "MEMBER", joinedAt: new Date("2026-05-10"), user: mockUsers[1] },
    ],
    documents: [],
    results: null,
  },
  {
    id: "comp-5",
    name: "Innovation Challenge ASEAN 2026",
    organizer: "ASEAN Foundation",
    website: "https://innovation-asean.org",
    level: "INTERNATIONAL",
    category: "INNOVATION_COMPETITION",
    description: "Kompetisi inovasi teknologi tingkat ASEAN.",
    prizePool: "$30,000",
    certificate: true,
    funding: true,
    incubation: true,
    status: "WON",
    startDate: new Date("2025-09-01"),
    endDate: new Date("2026-03-30"),
    createdAt: new Date("2025-08-15"),
    stages: [
      { id: "stage-inn-1", name: "Monitoring", order: 1, status: "COMPLETED", startDate: new Date("2025-08-15"), endDate: new Date("2025-08-31"), description: null },
      { id: "stage-inn-2", name: "Registration", order: 2, status: "COMPLETED", startDate: new Date("2025-09-01"), endDate: new Date("2025-09-30"), description: null },
      { id: "stage-inn-3", name: "Proposal", order: 3, status: "COMPLETED", startDate: new Date("2025-10-01"), endDate: new Date("2025-10-31"), description: null },
      { id: "stage-inn-4", name: "Development", order: 4, status: "COMPLETED", startDate: new Date("2025-11-01"), endDate: new Date("2026-01-31"), description: null },
      { id: "stage-inn-5", name: "Demo", order: 5, status: "COMPLETED", startDate: new Date("2026-02-01"), endDate: new Date("2026-02-28"), description: null },
      { id: "stage-inn-6", name: "Final", order: 6, status: "COMPLETED", startDate: new Date("2026-03-01"), endDate: new Date("2026-03-15"), description: null },
      { id: "stage-inn-7", name: "Result", order: 7, status: "COMPLETED", startDate: new Date("2026-03-30"), endDate: new Date("2026-03-30"), description: null },
    ],
    timeline: [
      { id: "tl-inn-1", title: "Registration", date: new Date("2025-09-30"), type: "DEADLINE", description: null },
      { id: "tl-inn-2", title: "Proposal Submission", date: new Date("2025-10-31"), type: "SUBMISSION", description: null },
      { id: "tl-inn-3", title: "Final Presentation", date: new Date("2026-03-15"), type: "PRESENTATION", description: null },
    ],
    tasks: [
      { id: "task-inn-1", competitionId: "comp-5", title: "Market Research", description: "Riset pasar ASEAN", status: "DONE", priority: "HIGH", assigneeId: "user-5", assignee: mockUsers[4], dueDate: new Date("2025-10-15"), createdAt: new Date("2025-09-10"), comments: [] },
      { id: "task-inn-2", competitionId: "comp-5", title: "Prototype Development", description: "Membuat prototype", status: "DONE", priority: "CRITICAL", assigneeId: "user-1", assignee: mockUsers[0], dueDate: new Date("2026-01-15"), createdAt: new Date("2025-11-01"), comments: [] },
      { id: "task-inn-3", competitionId: "comp-5", title: "Pitch Deck", description: "Membuat pitch deck", status: "DONE", priority: "HIGH", assigneeId: "user-2", assignee: mockUsers[1], dueDate: new Date("2026-03-01"), createdAt: new Date("2026-02-01"), comments: [] },
    ],
    deadlines: [
      { id: "dl-inn-1", competitionId: "comp-5", competition: null as any, title: "Registration", type: "REGISTRATION", date: new Date("2025-09-30"), description: null, daysRemaining: -256 },
      { id: "dl-inn-2", competitionId: "comp-5", competition: null as any, title: "Final Submission", type: "SUBMISSION", date: new Date("2026-03-15"), description: null, daysRemaining: -89 },
    ],
    teamMembers: [
      { id: "tm-inn-1", userId: "user-1", role: "LEADER", joinedAt: new Date("2025-08-20"), user: mockUsers[0] },
      { id: "tm-inn-2", userId: "user-2", role: "CO_LEADER", joinedAt: new Date("2025-08-25"), user: mockUsers[1] },
      { id: "tm-inn-3", userId: "user-5", role: "MEMBER", joinedAt: new Date("2025-09-01"), user: mockUsers[4] },
    ],
    documents: [
      { id: "doc-inn-1", competitionId: "comp-5", uploadedBy: "user-1", user: mockUsers[0], name: "Final_Proposal.pdf", type: "PROPOSAL", url: "/docs/final-proposal.pdf", size: 3072000, version: 3, createdAt: new Date("2025-10-25") },
      { id: "doc-inn-2", competitionId: "comp-5", uploadedBy: "user-2", user: mockUsers[1], name: "Pitch_Deck_Final.pptx", type: "PPT", url: "/docs/pitch-deck-final.pptx", size: 10240000, version: 5, createdAt: new Date("2026-03-10") },
    ],
    results: {
      id: "res-inn-1",
      competitionId: "comp-5",
      placement: "1st Place",
      score: 95.5,
      feedback: "Excellent innovation with strong market potential and technical implementation.",
      certificateUrl: "/certs/innovation-asean-2026.pdf",
    },
  },
];

export const mockActivities: ActivityLog[] = [
  { id: "act-1", userId: "user-1", user: mockUsers[0], competitionId: "comp-1", competition: mockCompetitions[0], action: "Mengupdate progress task", details: "Task 'Presentation Deck' diupdate ke In Progress", createdAt: new Date("2026-06-10T10:30:00") },
  { id: "act-2", userId: "user-2", user: mockUsers[1], competitionId: "comp-1", competition: mockCompetitions[0], action: "Mengunggah dokumen", details: "Mengunggah 'Presentation_Deck.pptx'", createdAt: new Date("2026-06-05T14:15:00") },
  { id: "act-3", userId: "user-4", user: mockUsers[3], competitionId: "comp-2", competition: mockCompetitions[1], action: "Menyelesaikan task", details: "Task 'Setup CTF Environment' selesai", createdAt: new Date("2026-03-25T09:00:00") },
  { id: "act-4", userId: "user-3", user: mockUsers[2], competitionId: "comp-3", competition: mockCompetitions[2], action: "Memulai literature review", details: "Memulai review 20 paper terkait", createdAt: new Date("2026-03-22T11:00:00") },
  { id: "act-5", userId: "user-5", user: mockUsers[4], competitionId: "comp-4", competition: mockCompetitions[3], action: "Mengevaluasi kompetisi", details: "Evaluasi BCC Unair 2026", createdAt: new Date("2026-05-15T16:30:00") },
  { id: "act-6", userId: "user-1", user: mockUsers[0], competitionId: "comp-5", competition: mockCompetitions[4], action: "Menang kompetisi", details: "Tim Cygnus memenangkan Innovation Challenge ASEAN 2026", createdAt: new Date("2026-03-30T08:00:00") },
  { id: "act-7", userId: "user-2", user: mockUsers[1], competitionId: "comp-1", competition: mockCompetitions[0], action: "Mengupdate stage", details: "Stage 'Demo' selesai", createdAt: new Date("2026-06-05T20:00:00") },
  { id: "act-8", userId: "user-3", user: mockUsers[2], competitionId: "comp-1", competition: mockCompetitions[0], action: "Mengintegrasikan AI", details: "Integrasi model AI selesai", createdAt: new Date("2026-04-20T15:45:00") },
];

export const mockKnowledgeBase: KnowledgeBaseArticle[] = [
  {
    id: "kb-1",
    title: "Tips Menang Hackathon",
    content: "1. Pilih ide yang unik dan feasible\n2. Fokus pada MVP yang solid\n3. Persiapkan pitch deck yang menarik\n4. Latihan presentasi sebelum demo day\n5. Jangan lupa dokumentasi teknis",
    category: "TIPS",
    tags: ["hackathon", "tips", "strategy"],
    authorId: "user-1",
    author: mockUsers[0],
    isTemplate: false,
    createdAt: new Date("2026-01-15"),
    updatedAt: new Date("2026-01-15"),
  },
  {
    id: "kb-2",
    title: "Template Proposal Hackathon",
    content: "## Struktur Proposal\n\n1. **Executive Summary**\n2. **Problem Statement**\n3. **Solution**\n4. **Technical Architecture**\n5. **Timeline**\n6. **Team**\n7. **Budget**\n\nPastikan setiap section jelas dan ringkas.",
    category: "TEMPLATE",
    tags: ["hackathon", "proposal", "template"],
    authorId: "user-2",
    author: mockUsers[1],
    isTemplate: true,
    createdAt: new Date("2026-01-10"),
    updatedAt: new Date("2026-02-01"),
  },
  {
    id: "kb-3",
    title: "Strategi CTF untuk Pemula",
    content: "1. Mulai dari kategori yang mudah (Web, Forensic)\n2. Pelajari tools standar (Burp Suite, IDA, Ghidra)\n3. Join community dan CTF platform\n4. Dokumentasikan setiap writeup\n5. Latihan rutin di platform seperti HackTheBox",
    category: "STRATEGY",
    tags: ["ctf", "cyber-security", "beginner"],
    authorId: "user-4",
    author: mockUsers[3],
    isTemplate: false,
    createdAt: new Date("2026-02-20"),
    updatedAt: new Date("2026-02-20"),
  },
  {
    id: "kb-4",
    title: "Lessons Learned: Innovation Challenge ASEAN",
    content: "## Apa yang Berhasil\n- Fokus pada problem yang real\n- Validasi ide dengan user interview\n- Prototype yang interaktif\n\n## Apa yang Perlu Ditingkatkan\n- Waktu presentasi lebih singkat\n- Lebih banyak user testing\n- Dokumentasi lebih rapi",
    category: "LESSONS_LEARNED",
    tags: ["innovation", "lessons-learned", "asean"],
    authorId: "user-1",
    author: mockUsers[0],
    isTemplate: false,
    createdAt: new Date("2026-04-05"),
    updatedAt: new Date("2026-04-05"),
  },
  {
    id: "kb-5",
    title: "Template Paper Research",
    content: "## Struktur Paper\n\n1. **Abstract**\n2. **Introduction**\n3. **Related Work**\n4. **Methodology**\n5. **Results**\n6. **Discussion**\n7. **Conclusion**\n8. **References**\n\nGunakan format IEEE atau ACM.",
    category: "TEMPLATE",
    tags: ["research", "paper", "template", "academic"],
    authorId: "user-3",
    author: mockUsers[2],
    isTemplate: true,
    createdAt: new Date("2026-03-01"),
    updatedAt: new Date("2026-03-01"),
  },
];

export const mockDashboardStats: DashboardStats = {
  totalActiveCompetitions: 4,
  totalFinishedCompetitions: 1,
  weeklyDeadlines: 3,
  totalActiveMembers: 5,
  overallProgress: 72,
};

export function getAllDeadlines(): Deadline[] {
  const deadlines: Deadline[] = [];
  mockCompetitions.forEach((comp) => {
    comp.deadlines.forEach((dl) => {
      dl.competition = comp;
      dl.daysRemaining = getDaysRemaining(dl.date);
      deadlines.push(dl);
    });
  });
  return deadlines.sort((a, b) => a.date.getTime() - b.date.getTime());
}

function getDaysRemaining(date: Date): number {
  const now = new Date();
  const target = new Date(date);
  const diff = target.getTime() - now.getTime();
  return Math.ceil(diff / (1000 * 60 * 60 * 24));
}
